name: my-first-workflow

on: 
  workflow_dispatch: 
  schedule:
  # Runs daily at 00:00 UTC
  - cron: "0 0 * * *"

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: hello world
        run: echo "hello world"
